workspace(name = "example")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")

skylib_version = "1.0.3"

http_archive(
    name = "bazel_skylib",
    sha256 = "1c531376ac7e5a180e0237938a2536de0c54d93f5c278634818e0efc952dd56c",
    type = "tar.gz",
    url = "https://mirror.bazel.build/github.com/bazelbuild/bazel-skylib/releases/download/{}/bazel-skylib-{}.tar.gz".format(skylib_version, skylib_version),
)

rules_proto_commit = "dcf9e47b0df2218ca33e02a1a51803ab3134f42d"
http_archive(
    name = "rules_proto",
    sha256 = "d31d04a8bb1912fbc122bcc7eea49964c9b75c6e091ac3f9deea2bb6a8025a4a",
    strip_prefix = "rules_proto-%s" % rules_proto_commit,
    urls = [
        "https://github.com/bazelbuild/rules_proto/archive/%s.tar.gz" % rules_proto_commit,
    ],
)

load("@rules_proto//proto:repositories.bzl", "rules_proto_dependencies", "rules_proto_toolchains")

rules_proto_dependencies()

rules_proto_toolchains()

# scala
rules_scala_version = "9c0f6b942b2a2555c41b622b41280a45bf7cb92e"  # update this as needed

http_archive(
    name = "io_bazel_rules_scala",
    sha256 = "e2db6f08109d4ec11cac07c98ceabdbc5cf0b8adbd798d35037f475836d81a23",
    strip_prefix = "rules_scala-%s" % rules_scala_version,
    type = "zip",
    url = "https://github.com/bazelbuild/rules_scala/archive/%s.zip" % rules_scala_version,
)

load("@io_bazel_rules_scala//:scala_config.bzl", "scala_config")

scala_config("2.13.12")

load("@io_bazel_rules_scala//scala:scala.bzl", "scala_repositories")

register_toolchains("//:toolchain")

scala_repositories()
