name: Release

on:
  push:
    branches:
      - main
    tags: [v*]

jobs:
  build:
    name: Run the release
    runs-on: ubuntu-latest
    timeout-minutes: 40
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix flake check
      - run: nix develop --command sbt root/assembly
      - run: echo "DERIVED_VERSION=release-${{ github.ref_name }}" >> "$GITHUB_OUTPUT"
        id: version
        if: startsWith(github.ref, 'refs/tags/v')
      - name: Update the docs
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          DERIVED_VERSION: ${{ steps.version.outputs.DERIVED_VERSION }}
        run: |
          git fetch origin main
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git rebase origin/main

          ARTIFACT_HASH=$(nix-hash --flat --type sha256 target/mezel.jar)
          sed -i "s|sha256 =.*$|sha256 = \"${ARTIFACT_HASH}\",|" rules/load_mezel.bzl
          sed -i "s|version =.*$|version = \"${DERIVED_VERSION}\"|" rules/load_mezel.bzl

          git add rules/load_mezel.bzl
          git commit -m "automatic update of mezel artifact location to ${{ github.ref_name }}"
          ARTIFACT_COMMIT_HASH=$(git rev-parse HEAD)
          git push origin HEAD:main

          git tag -a $DERIVED_VERSION -m "Release ${{ github.ref_name }}"
          git push origin refs/tags/$DERIVED_VERSION

          URL="${{ github.server_url }}/${{ github.repository }}/archive/${ARTIFACT_COMMIT_HASH}.zip"
          nix-shell -p wget --command "wget ${URL} -O /tmp/mezel.zip"
          REPO_HASH=$(nix-hash --flat --type sha256 /tmp/mezel.zip)
          README_SHA_LINE_NUM=$(expr $(grep -n -m 1 "name = \"mezel\"" README.md | grep -o -P "\d*") + 1)
          sed -i "${README_SHA_LINE_NUM}s|sha256.*$|sha256 = \"${REPO_HASH}\",|" README.md
          sed -i "s|mezel_version =.*$|mezel_version = \"${ARTIFACT_COMMIT_HASH}\"|" README.md

          git add README.md
          git commit -m "automatic update of mezel docs for ${{ github.ref_name }}"
          git push origin HEAD:main
      - if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.version.outputs.DERIVED_VERSION }}
          files: |
            target/mezel.jar
